package frc.robot;

/** GENERATED BY shooting_regression.py DO NOT EDIT BY HAND */
public class ShootingRegression {
    public static double calculateVelocityMetersPerSec(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        return 5.98184266941433 + 0.38990881243173814 * x + -0.3240728526264065 * y + -0.032856643709916915 * x * y + 0.025454308918660514 * x * x + 0.053982613756920435 * y * y + -0.0004056322482506517 * x * x * y * y;
    }

    public static double calculateHoodAngleRad(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        // Hood angle for vertical shot is 0°
        // Shooting sim angle for vertical shot is 90°
        // Shooting sim angle for 15° from vertical is 75°
        // Therefore, hood angle = 90° - shooting sim angle
        return Math.PI / 2.0 - (1.5845707897494905 + -0.19498035526928892 * x + 0.1384925000286077 * y + -0.007813621427349484 * x * y + 0.015332123168953871 * x * x + 0.006460303639596439 * y * y + -5.363788872225973e-05 * x * x * y * y);
    }
}
