// spotless:off
package frc.robot.autos;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;



/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CanadianDepot_FirstPass = new ChoreoTraj(
        "CanadianDepot_FirstPass",
        OptionalInt.empty(),
        2.97887,
        new Pose2d(6.34, 7.55, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(5.71094, 5.53025, Rotation2d.fromRadians(2.35619))
    );
    public static final ChoreoTraj CanadianOutpost_FirstPass = new ChoreoTraj(
        "CanadianOutpost_FirstPass",
        OptionalInt.empty(),
        3.18619,
        new Pose2d(6.43947, 0.64949, Rotation2d.fromRadians(1.5708)),
        new Pose2d(5.7009, 2.41898, Rotation2d.fromRadians(-1.99499))
    );
    public static final ChoreoTraj OrbitPassingOutpost_Score = new ChoreoTraj(
        "OrbitPassingOutpost_Score",
        OptionalInt.empty(),
        9.20263,
        new Pose2d(3.56254, 0.59382, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.81781, 0.76175, Rotation2d.fromRadians(-2.43314))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj OrbitPassingOutpost_Score$0 = new ChoreoTraj(
        "OrbitPassingOutpost_Score",
        OptionalInt.of(0),
        1.62952,
        new Pose2d(3.56254, 0.59382, Rotation2d.fromRadians(3.14159)),
        new Pose2d(2.8259, 3.07236, Rotation2d.fromRadians(-2.65572))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj OrbitPassingOutpost_Score$1 = new ChoreoTraj(
        "OrbitPassingOutpost_Score",
        OptionalInt.of(1),
        7.573109999999999,
        new Pose2d(2.8259, 3.07236, Rotation2d.fromRadians(-2.65572)),
        new Pose2d(0.81781, 0.76175, Rotation2d.fromRadians(-2.43314))
    );
    public static final ChoreoTraj CanadianDepot_SecondPath = new ChoreoTraj(
        "CanadianDepot_SecondPath",
        OptionalInt.empty(),
        17.95704,
        new Pose2d(5.77121, 7.55, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(5.71197, 5.52342, Rotation2d.fromRadians(2.35619))
    );
    public static final ChoreoTraj CanadianOutpost_SecondPass = new ChoreoTraj(
        "CanadianOutpost_SecondPass",
        OptionalInt.empty(),
        2.9007,
        new Pose2d(6.39331, 0.60333, Rotation2d.fromRadians(1.5708)),
        new Pose2d(5.51626, 2.57285, Rotation2d.fromRadians(-2.62245))
    );
    public static final ChoreoTraj OrbitPassingOutpost_Collect = new ChoreoTraj(
        "OrbitPassingOutpost_Collect",
        OptionalInt.empty(),
        8.42389,
        new Pose2d(5.87427, 0.59382, Rotation2d.fromRadians(0)),
        new Pose2d(5.86254, 0.59382, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj OrbitPassingOutpost_Collect$0 = new ChoreoTraj(
        "OrbitPassingOutpost_Collect",
        OptionalInt.of(0),
        1.38036,
        new Pose2d(5.87427, 0.59382, Rotation2d.fromRadians(0)),
        new Pose2d(6.65968, 2.99812, Rotation2d.fromRadians(0.19097))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj OrbitPassingOutpost_Collect$1 = new ChoreoTraj(
        "OrbitPassingOutpost_Collect",
        OptionalInt.of(1),
        4.5685,
        new Pose2d(6.65968, 2.99812, Rotation2d.fromRadians(0.19097)),
        new Pose2d(7.6807, 3.89817, Rotation2d.fromRadians(0.28055))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj OrbitPassingOutpost_Collect$2 = new ChoreoTraj(
        "OrbitPassingOutpost_Collect",
        OptionalInt.of(2),
        2.4750300000000003,
        new Pose2d(7.6807, 3.89817, Rotation2d.fromRadians(0.28055)),
        new Pose2d(5.86254, 0.59382, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj CanadianOutpsot_lessAgroSecondPass = new ChoreoTraj(
        "CanadianOutpsot_lessAgroSecondPass",
        OptionalInt.empty(),
        3.84442,
        new Pose2d(5.77121, 0.64949, Rotation2d.fromRadians(1.5708)),
        new Pose2d(5.7009, 2.41898, Rotation2d.fromRadians(-1.99499))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("CanadianDepot_FirstPass", CanadianDepot_FirstPass),
        Map.entry("CanadianOutpost_FirstPass", CanadianOutpost_FirstPass),
        Map.entry("OrbitPassingOutpost_Score", OrbitPassingOutpost_Score),
        Map.entry("OrbitPassingOutpost_Score$0", OrbitPassingOutpost_Score$0),
        Map.entry("OrbitPassingOutpost_Score$1", OrbitPassingOutpost_Score$1),
        Map.entry("CanadianDepot_SecondPath", CanadianDepot_SecondPath),
        Map.entry("CanadianOutpost_SecondPass", CanadianOutpost_SecondPass),
        Map.entry("OrbitPassingOutpost_Collect", OrbitPassingOutpost_Collect),
        Map.entry("OrbitPassingOutpost_Collect$0", OrbitPassingOutpost_Collect$0),
        Map.entry("OrbitPassingOutpost_Collect$1", OrbitPassingOutpost_Collect$1),
        Map.entry("OrbitPassingOutpost_Collect$2", OrbitPassingOutpost_Collect$2),
        Map.entry("CanadianOutpsot_lessAgroSecondPass", CanadianOutpsot_lessAgroSecondPass)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
}
// spotless:on
