package frc.robot.shooting;

/** GENERATED BY shooting_regression.py DO NOT EDIT BY HAND */
public class PassingRegression {
    /** Passing angle **from the horizontal**. Note that hood angle is from the vertical. */
    public static final double angleRad = 0.8726646259971648;

    public static double calculateVelocityMetersPerSec(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        return 2.1989040016737915 + 1.1528038777245762 * x + -0.8946041893039075 * y + 0.0019250078252935692 * x * y + -0.02153204674672702 * x * x + 0.03579217928982277 * y * y;
    }
}
