package frc.robot.shooting;

/** GENERATED BY shooting_regression.py DO NOT EDIT BY HAND */
public class PassingRegression {
    /** Passing angle **from the horizontal**. Note that hood angle is from the vertical. */
    public static final double angleRad = 0.8726646259971648;

    public static double calculateVelocityMetersPerSec(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        return 2.088798145000358 + 1.0862137834657881 * x + -0.8946198705131636 * y + 0.0019533734625622854 * x * y + -0.02022931450517936 * x * x + 0.03746957928129486 * y * y;
    }
}
