package frc.robot.shooting;

/** GENERATED BY shooting_regression.py DO NOT EDIT BY HAND */
public class ScoringRegression {
    /** Distance is measured as the distance in the XY plane between the fuel exit point and the target. */
    public static double calculateVelocityMetersPerSec(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        return 5.751897914397706 + 0.5776343971838904 * x + -0.1357115201396799 * y + -0.055837730336917524 * x * y + 0.0036986042858344614 * x * x + 0.0519691360429011 * y * y;
    }

    /**
     * Calculate scoring angle **from the horizontal**. Note that hood angle is from the vertical.
     * Distance is measured as the distance in the XY plane between the fuel exit point and the target.
     */
    public static double calculateAngleRad(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        return 1.4697691065413687 + -0.11289504365249894 * x + 0.14968881785905883 * y + -0.009685035977833751 * x * y + 0.0067097570346152016 * x * x + 0.00429172180148469 * y * y;
    }

    /** Distance is measured as the distance in the XY plane between the fuel exit point and the target. */
    public static double calculateToFSeconds(double distanceMeters, double radialRobotVelocityMetersPerSec) {
        double x = distanceMeters;
        double y = radialRobotVelocityMetersPerSec;
        return 0.922068073602401 + 0.10095392988593399 * x + 0.0012929927195102324 * y + -7.278571804386206e-05 * x * y + -0.00230587061322973 * x * x + 9.514973955077307e-05 * y * y;
    }
}
